### ISSUE TITLE
Piwik settings missing. Add settings to your settings.json file

### ISSUE THREAD

**Issue by johnrackles** [appjitsu/piwik#10]
I'm getting this error, yet I've added the settings to my settings.json file.

This is my settings.json without the real url:

```
{
  "public": {

  },
  "piwik": {
    "url": "http://my_piwik_url/piwik.php",
    "site_id": 13
  }
}
```

any idea what might be wrong?

**Comment by bartwr** [comment]
Did you start Meteor using: `meteor --settings settings.json` ?
