### ISSUE TITLE
Error running app after installation

### ISSUE THREAD

**Issue by edionmelarosa** [appjitsu/piwik#8]
App not running after installation with error of:
 " TypeError: Cannot read property 'piwik' of undefined
W20150902-18:23:10.775(8)? (STDERR)     at Package (packages/appjitsu:piwik/server/piwik.js:2:1) ".

More info: 
 - I added "piwik" object on my settings file.
 - Im on "1.1.0.3" version
 - im on Ubuntu

This error is weird why it isn't reading the "piwik" obj on my settings file.

**Comment by appjitsu** [comment]
Please post your settings file (without sensitive data of course).

**Comment by rakesh19487** [comment]
I am also having the same issues, i just followed the instructions and added following in my setting.json file.

{
 "piwik": {
     "url": "http://your_piwik_server_url/piwik.php",
     "site_id": site id goes here
   }
}

**Comment by edionmelarosa** [comment]
Heres my full settings file.

{	
	"public": {
		"imageUri": "imageUri",
		"publicDataOrders": [
	      
		]
	},
	"server": {
		"baseUri": "baseUri",
		"PrivateDataUri":  "PrivateDataUri",
		"PublicDataUri": "PublicDataUri"
	},
	"auth": {
		"linkedin": {
			"clientId": "clientId",
			"clientSecret": "clientSecret",
			"state": "state"
		}
	},
	"piwik": {
	    "url": "my piwik url",
	    "site_id": 9
	}
}

**Comment by appjitsu** [comment]
Try the newest version 0.0.5 on atmosphere and let me know your results.
